%%{init: {'theme': 'base', 'themeVariables': { 'lineColor': '#404040'}}}%%

        %% GenPipes Schema for dnaseq.py
        %% Ref: https://bitbucket.org/mugqic/genpipes/src/master/pipelines/dnaseq/
        %% Author Shaloo Shalini <shalz@hotmail.com>
        %% -t somatic_fastpass

        graph LR
        Node1{{ 1.<br/> GATK<br/>SAM<br/>to FASTQ }}:::nodefill
        Node2{{ 2.<br/> Trim<br/>FastP }}:::nodefill
        Node3{{ 3.<br/> BWA<br/>Mem2<br/>SAM Tools<br/>Sort }}:::nodefill
        Node4{{ 4.<br/> GATK<br/>Mark<br/>Duplicates }}:::nodefillblack
        Node5{{ 5.<br/> Set<br/>Interval List }}:::nodefill
        Node6{{ 6.<br/> Sequenza }}:::nodefill
        Node7{{ 7.<br/> Raw MPileup }}:::nodefill
        Node8{{ 8.<br/> Paired<br/>Varscan2 }}:::nodefill
        Node9{{ 9.<br/> Merge<br/>Varscan2 }}:::nodefill
        Node10{{ 10.<br/> Preprocess<br/>VCF }}:::nodefill
        Node11{{ 11.<br/> CNVKit<br/>Batch }}:::nodefill
        Node12{{ 12.<br/> Filter<br/>Germline }}:::nodefill
        Node13{{ 13.<br/> Report CPSR }}:::nodefill
        Node14{{ 14.<br/> Filter Somatic }}:::nodefill      
        Node15{{ 15.<br/> Report PCGR }}:::nodefill
        Node16{{ 16.<br/> Conpair<br/>Concordance<br/>Contamination }}:::nodefill
        Node17{{ 17.<br/> Metrics<br/>DNA<br/>Picard }}:::nodefill
        Node18{{ 18.<br/> DNA Sample <br/> MosDepth Metrics }}:::nodefill
        Node19{{ 19.<br/> Run<br/>MultiQC }}:::nodefill
        Node20{{ 20.<br/> Sym Link<br/>Report }}:::nodefill
        Node21{{ 21.<br/> Sym Link<br/>FastQ Pair }}:::nodefill
        Node22{{ 22.<br/> Sym Link<br/>Panel }}:::nodefill
        Node23{{ 23.<br/> Cram<br/>Output  }}:::nodefill

        Input1[[fa:fa-file-archive-o .BAM]]
        Input2[[fa:fa-file-archive-o .FASTQ]]

   
        MultiQCOP([fa:fa-sticky-note-o Report ])
        CramOP([fa:fa-sticky-note-o Report ])

        Input1 --> Node1
        Input2 --> Node2

        Node1 -.-> Node2 & Node21
        Node2 -.-> Node3 -.-> Node4
        Node4 -.-> Node5 & Node6 & Node7 & Node11 & Node16 & Node17 & Node18 & Node23
        Node7 -.-> Node8 -.-> Node9 -.-> Node10
        Node9 -.-> Node11 & Node14
        Node10 -.-> Node12 -.-> Node13
        Node11 & Node13 & Node14 -.-> Node15
        Node2 & Node4 & Node16 & Node17 & Node18 -.-> Node19
        Node19 -.-> Node20
        Node9 & Node12 & Node13 & Node14 & Node15 -.-> Node22

        Node19 --> MultiQCOP
        Node23 --> CramOP

        subgraph readSetSteps[" "]
          Node1
          Node2
          Node3
          MTSOutput
        end
        subgraph sampleSetSteps[" "]
          Node5
          Node6
          Node7
          Node8
          Node9
          Node10
          Node11
          Node12
          Node13
          Node14
          Node15
          Node16
          Node17
          Node18
          Node19
          Node20
          Node21
          Node22
          Node23
          MultiQCOP
          CramOP
        end

        classDef greenRect fill:#E4FBF4,stroke:white
        class readSetSteps greenRect
        classDef blueRect fill:#DEF6FC,stroke:white
        class sampleSetSteps blueRect
        classDef nodefill fill:#ffffff,stroke:gray,stroke-width:2px
        classDef nodefillblack fill:black,stroke:black,color:white,stroke-width:2px
